### ISSUE TITLE
Decoding 'left_right_balance' field as a UInt8

### ISSUE THREAD

**Issue by tevendale** [roznet/FitFileParser#4]
I'm trying to decode the '_left_right_balance_' field in a Record message.

I'm expecting to get a '_left_right_balance_' (actually a UInt8) value, but I'm getting a string, something like '_FitField(withName: left_right_balance_178_'.

I've had a look through the 'fitsdkparser.py' but I can't quite work out how the parts of the swift files are generated for different field types.

Sample file attached
[LRBalanceTest.fit.zip](https://github.com/roznet/FitFileParser/files/8369569/LRBalanceTest.fit.zip)
.

**Comment by roznet** [comment]
Ah! yes, the data is reported as a "type" which seem to be some formula to extract a number, while the code assumes that types are just basically an enum, so it gets confused.

Here is the definition for `left_right_balance` in the Profile.xlsx

|left_right_balance | uint8 |   |   |  
|-- | -- | -- | -- | --
|  |   | mask | 0x7F | % contribution
|  |   | right | 0x80 | data corresponds to right if set, otherwise unknown

I'll add that logic and try to fix it this weekend.

Thanks for providing the sample fit file, so I can test, I don't have that kind of data myself ...
